### ISSUE TITLE
请问大佬，是我的使用方法不对吗？为什么安装了apk后快捷键还可以使用

### ISSUE THREAD

**Issue by 1Mamello1** [CwithW/MiuiPadMeta#4]
设备是小米Pad5 Pro，14.0.11.0版本MIUI 13版本安卓。

**Comment by CwithW** [comment]
小米平板5Pro 14.0.5.0测试可用，要在Xposed/LSPosed管理器里启用模块，之后重启平板

米米不给我推送14.0.11.0，我暂时无法测试这个系统版本

**Comment by 1Mamello1** [comment]
刷回13.1.4后完美解决了，谢谢大佬的分享
